### ISSUE TITLE
Labyrinthe : items/potions : ralentissement

### ISSUE THREAD

**Issue by faradaye** [Cerb1999/Maze#27]
Différents items : 
- Ralentissement du héros
- Ralentissement de tous les monstres
- Accélération des monstres

**Comment by LarbiAmineGIT** [comment]
Ralentissement du héros terminé

**Comment by LarbiAmineGIT** [comment]
Ralentissement de tout les monstres terminé

**Comment by LarbiAmineGIT** [comment]
Accélération de tout les monstres terminé
